name: Autograding Tests
'on':
  - push
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # PASSO DE DEPURAÇÃO: Isso vai nos mostrar a estrutura exata de pastas.
      - name: List files in the repository
        run: ls -R

      - name: Grant execute permission for gradlew
        # ADICIONADO: Diz ao comando para rodar dentro da subpasta do projeto
        working-directory: ./fibonacci-gabriel1ns
        run: chmod +x gradlew

      - name: fibonacci test
        id: fibonacci-test
        uses: classroom-resources/autograding-command-grader@v1
        # ADICIONADO: Diz ao teste para rodar dentro da subpasta do projeto
        working-directory: ./fibonacci-gabriel1ns
        with:
          test-name: fibonacci test
          setup-command: ''
          command: ./gradlew test
          timeout: 5
          max-score: 100
          # ---
      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        with:
          runners: fibonacci-test