name: Autograding Tests
'on':
  - push
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: fibonacci test
        id: fibonacci-test
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: fibonacci test
          setup-command: ''
          # Comando final e limpo, sem depuração
          command: ./gradlew test
          timeout: 10
          max-score: 100
          # ---
      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        with:
          runners: fibonacci-test